### ISSUE TITLE
cmake 3.18

### ISSUE THREAD

**Issue by berndhahnebach** [dr-bill-c/MYSTRAN#14]
Is really cmake 3.18 needed for Mystran? On Debian buster only 3.13.4 is installed?

cheers bernd

**Comment by berndhahnebach** [comment]
just found the answer myself. It is not IMHO. I just downloaded and extracted superlu myself and deleted the part in the cmake file.

sorry for the noise ... Bernd

**Comment by zchlrnr** [comment]
Hey Bernd,

Glad to see you stopping by, and good lordy I'm happy to see you found a way to grab it.

I've typically been forced to use snap for the superlu compilation, or get cmake from source for my arch instructions.

I'm working on an enhanced readme for more in depth installation and compilation instructions in my mystran repo. I'd love to know why you did what you did rather than grabbing cmake from upstream, and specifically HOW you did what you did, as if it was easier, it should be how we do it.

See you on the FreeCAD forums, and I hope you like mystran!

- Zach

**Comment by berndhahnebach** [comment]
- cmake should be minimum 3.8 in debian buster is 3.13.4 thus I changed this in cmake
- some problem came up with downloading, unpacking and copieng SuperLu
- I did not look into it why it did not work. I just made the process maually and deleted this part in cmake
- after this cmake run without any problem
